INT8_QMIN = -128
INT8_QMAX = 127
INT32_QMIN = -2147483648
INT32_QMAX = 2147483647

TRAINABLE_LAYERS = ("conv1", "conv2", "fc1", "fc2")

DEFAULT_LR = 0.001
DEFAULT_FLOAT_LR = DEFAULT_LR
DEFAULT_QAT_LR = DEFAULT_LR
DEFAULT_QUANTIZED_LR = DEFAULT_LR
DEFAULT_QAS_LR = DEFAULT_LR

DEFAULT_BATCH_SIZE = 128
DEFAULT_TEST_BATCH_SIZE = 512
DEFAULT_NUM_WORKERS = 2
DEFAULT_MOMENTUM = 0.9
DEFAULT_SEED = 0

DEFAULT_BASELINE_RUN_NAME = "baseline"
DEFAULT_PTQ_CHECKPOINT_PATH = "common/baseline/artifacts/baseline_ptq/checkpoint.pt"
