INT8_QMIN = -128
INT8_QMAX = 127
INT32_QMIN = -2147483648
INT32_QMAX = 2147483647

TRAINABLE_LAYERS = ("conv1", "conv2", "fc1", "fc2")

DEFAULT_LR = 0.001
DEFAULT_FLOAT_LR = DEFAULT_LR
DEFAULT_QAT_LR = DEFAULT_LR
DEFAULT_FINETUNE_LR = 0.00001
DEFAULT_QUANTIZED_LR = DEFAULT_FINETUNE_LR
DEFAULT_QAS_LR = DEFAULT_FINETUNE_LR

DEFAULT_BASELINE_EPOCHS = 20
DEFAULT_BASELINE_BATCH_SIZE = 128
DEFAULT_BASELINE_TEST_BATCH_SIZE = 512
DEFAULT_BASELINE_NUM_WORKERS = 2

DEFAULT_FINETUNE_EPOCHS = 1
DEFAULT_FINETUNE_BATCH_SIZE = 4
DEFAULT_FINETUNE_TEST_BATCH_SIZE = 1
DEFAULT_FINETUNE_NUM_WORKERS = 0

DEFAULT_MOMENTUM = 0.9
DEFAULT_SEED = 0

DEFAULT_BASELINE_RUN_NAME = "baseline"
DEFAULT_PTQ_CHECKPOINT_PATH = "common/baseline/artifacts/baseline_ptq/checkpoint.pt"
DEFAULT_QAS_RUN_NAME = "qas"
DEFAULT_TORCH_QAS_RUN_ROOT = "torch_impl/artifacts"
DEFAULT_NPY_QAS_RUN_ROOT = "npy_impl/artifacts"
